In [50]:
# Initialize Otter
import otter
grader = otter.Notebook("05-exercise-pids2026.ipynb")

<div style='background:linear-gradient(135deg,#FFD6EA 0%,#FFC7E3 100%); padding:28px 32px; border-radius:10px; color:black; font-family:Arial,sans-serif;'>
  <div style='display:flex; align-items:center; gap:18px;'>
    <span style='font-size:3em;'>🎲</span>
    <div>
      <h1 style='margin:0; font-size:1.8em; letter-spacing:1px;'>Exercise Sheet 5</h1>
      <p style='margin:4px 0 0; font-size:1em; opacity:0.85;'>
        Practical Introduction to Data Science · University of Basel · Spring 2026</p>
    </div>
  </div>
  <hr style='border:none; border-top:1px solid rgba(255,255,255,0.3); margin:18px 0 14px;'>
  <div style='display:flex; gap:28px; font-size:0.92em; opacity:0.9;'>
    <span>📈 Probabilities</span>
    <span>🧠 Conditional Probabilities</span>
    <span>🎯 15 Points</span>
  </div>
</div>

# Exercise sheet 5
**Hello everyone!**
Topics of this exercise sheet are:
* Probabilities
* Conditional Probabilities


Please let us know if you have questions or problems! <br>
Contact us during the exercise session or on [Piazza](https://piazza.com/class/m78z4stm7o55ed).

**Automatic Feedback**

This notebook can be automatically graded using Otter grader. To find how many points you get, simply run `grader.check_all()` from a new cell.

In [51]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## 1 (6 points)
Let's start with some basic probability terms.

### 1a (1 point)
What is $\Omega$ for 3 coin tosses? Use the Python 'set' data structure with tuples to describe each possible outcome. Name the result `omega_three_coin_tosses`. Use 0 for tails and 1 for heads.

* **Recall:** $\Omega$ is the set of all possible outcomes of an experiment. 
* **Hint:** Make use of pythons [set comprehensions](https://python-reference.readthedocs.io/en/latest/docs/comprehensions/set_comprehension.html)

In [52]:
class Question1a:
    # omega_three_coin_tosses = set(...)
    omega_three_coin_tosses ={(i,j,k)
                             for i in [0,1]
                             for j in [0,1]
                             for k in [0,1]}
    print( omega_three_coin_tosses)

{(1, 0, 1), (1, 1, 0), (0, 1, 0), (0, 0, 0), (1, 0, 0), (0, 0, 1), (1, 1, 1), (0, 1, 1)}

In [ ]:
grader.check("Question 1a")

### 1b (1 point)
We roll two standard dice.
What is $\Omega$ for "We roll the same number twice?"

Save your answer as a 'set' data structure under the name `omega_same_number_twice`.

In [53]:
class Question1b:
    omega_same_number_twice =set()
    for i in range(1,7):
        omega_same_number_twice.add((i,i))
    print(omega_same_number_twice)

{(4, 4), (5, 5), (1, 1), (3, 3), (2, 2), (6, 6)}

In [54]:
grader.check("Question 1b")

Question 1b results: All test cases passed!

### 1c (1 point)
We roll two standard dice. What is the probability ($\mathbb{P}$) for the sum of the two dice being lower than 27?
Put the result in a variable named `probability_lower_27` and make sure to right the probability as a fraction.

For instance, if the question was "what is the probability having two tails while flipping consecutively two coins?", your answer should be 1/4 and not 0.25, because there is one event in the set of all 4 possible events where that appears. We ask for this specific format to make sure that you understand how to compute it.

In [55]:
class Question1c:
    probability_lower_27 =1.0

In [56]:
grader.check("Question 1c")

Question 1c results: All test cases passed!

### 1d (1 point)
We roll two standard dice. What is the probability for the sum of the two dice being lower or equal to 6?
Put the result in a variable named `probability_lower_6` and make sure to right the probability as a fraction.

In [57]:
class Question1d:
    probability_lower_6 = 5/12

In [58]:
grader.check("Question 1d")

Question 1d results: All test cases passed!

### 1e (2 point)
We roll two standard dice. If the first die shows a "6", what is the probability of the sum of the two dice being equal or higher than 8?
Put the result in a variable named `probability_higher_8` and make sure to right the probability as a fraction.

In [59]:
class Question1e:
    probability_higher_8 =5/6

In [60]:
grader.check("Question 1e")

Question 1e results: All test cases passed!

## 2 (5 points)
We will work with a dataset about strokes (sourced from [Kaggle](https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset)).

In [61]:
stroke_df = pd.read_csv("healthcare-dataset-stroke-data.csv")
stroke_df

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0

### 2a (1 point)
For a patient contained in this dataset, what is the probability that they had a stroke $\mathbb{P}(\text{stroke})$?

Make sure to save your answer in the variable `probability_stroke` and that it is a float value

In [62]:
class Question2a:
    probability_stroke = stroke_df["stroke"].mean()
    print(probability_stroke)

0.0487279843444227

In [63]:
grader.check("Question 2a")

Question 2a results: All test cases passed!

### 2b (1 point)
For a patient contained in this dataset who had heart disease (heart_disease = 1), what is the probability that they had a stroke $\mathbb{P}(\text{stroke|heart\_disease})$?

**Reminder:** the conditional probability is defined as:
$$ \mathbb{P}(A|B) = \frac{\mathbb{P}(A \cap B)}{\mathbb{P}(B)}$$
Make sure to save your answer in the variable `probability_stroke_heart_disease` and that it is a float value.

In [64]:
class Question2b:
    ...
    probability_stroke_heart_disease =stroke_df[stroke_df["heart_disease"]==1]["stroke"].mean()
    print(probability_stroke_heart_disease)

0.17028985507246377

In [65]:
grader.check("Question 2b")

Question 2b results: All test cases passed!

### 2c (2 points)
What is the probability of $P(\text{stroke|Female})$?
Make sure to save your answer in the variable `probability_stroke_female` and that it is a float value.

In [66]:
class Question2c:
    ...
    probability_stroke_female =stroke_df[stroke_df["gender"]=="Female"]["stroke"].mean()
    print(probability_stroke_female)

0.047094188376753505

In [67]:
grader.check("Question 2c")

Question 2c results: All test cases passed!

### 2d (1 point)
What is the probabolity of $P(\text{stroke|Male})$?

Make sure to save your answer in the variable `probability_stroke_male` and that it is a float value.

In [68]:
class Question2d:
    ...
    probability_stroke_male =stroke_df[stroke_df["gender"]=="Male"]["stroke"].mean()
    print(probability_stroke_male)

0.05106382978723404

In [69]:
grader.check("Question 2d")

Question 2d results: All test cases passed!

### 2e (4 points)
According to the [Mayo Clinic](https://www.mayoclinic.org/diseases-conditions/diabetes/diagnosis-treatment/drc-20371451), a "blood sugar level less than 140 mg/dL (7.8 mmol/L) is normal".

* Make a new column called "high_glucose" in the dataframe `stroke_df` that has a 1 if the `avg_glucose_level` measurement was equal to or higher than 140, and a 0 otherwise.

In [90]:
class Question2e:
 stroke_df["high_glucose"]=(stroke_df["avg_glucose_level"]>=140).astype(int)
 
 display(stroke_df)

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke,high_glucose
0,9046,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1,1
1,51676,Female,61.0,0,0,Yes,Self-employed,Rural,202.21,NaN,never smoked,1,1
2,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1,0
3,60182,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1,1
4,1665,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5105,18234,Female,80.0,1,0,Yes,Private,Urban,83.75,NaN,never smoked,0,0
5106,44873,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.0,never smoked,0,0
5107,19723,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.6,never smoked,0,0
5108,37544,Male,51.0,0,0,Yes,Private,Rural,166.29,25.6,formerly smoked,0,1
5109,44679,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.2,Unknown,0,0

In [91]:
grader.check("Question 2e - 1")

Question 2e - 1 results: All test cases passed!

* Use this new column to calculate $\mathbb{P}(\text{stroke | high\_glucose})$.
Make sure to save your answer in the variable `probability_stroke_high_glucose` and that it is a float value.

In [92]:
class Question2e2:
    ...
    probability_stroke_high_glucose =stroke_df[stroke_df["high_glucose"]==1]["stroke"].mean()
    print(probability_stroke_high_glucose)

0.11327649208282582

In [93]:
grader.check("Question 2e - 2")

Question 2e - 2 results: All test cases passed!

* Calculate $\mathbb{P}(\text{high\_glucose|stroke})$
Make sure to save your answer in the variable `probability_high_glucose_stroke` and that it is a float value.

In [95]:
class Question2e3:
    ...
    probability_high_glucose_stroke = stroke_df[stroke_df["stroke"]==1]["high_glucose"].mean()
    print(probability_high_glucose_stroke)

0.37349397590361444

In [96]:
grader.check("Question 2e - 3")

Question 2e - 3 results: All test cases passed!

---

To double-check your work, the cell below will rerun all of the autograder tests.

In [97]:
grader.check_all()

Question 1a results: All test cases passed!

Question 1b results: All test cases passed!

Question 1c results: All test cases passed!

Question 1d results: All test cases passed!

Question 1e results: All test cases passed!

Question 2a results: All test cases passed!

Question 2b results: All test cases passed!

Question 2c results: All test cases passed!

Question 2d results: All test cases passed!

Question 2e - 1 results: All test cases passed!

Question 2e - 2 results: All test cases passed!

Question 2e - 3 results: All test cases passed!